# run: conda env create --file environment.yml
# to update run: conda env update --file environment.yml

name: Understand_TreeSHAP
dependencies:
  - python>=3.8
  - numpy=1.20.3
  - matplotlib=3.3.4
  - pandas=1.2.4
  - pip>=21.0.1
  - pip:
    - scikit-learn==1.1.1
    - numba==0.54.0
    - shap
    - graphviz
    - xgboost
